const hosting = [
    {
      id: 1,
      name: 'Hosting small',
      url: 'https://my.donhoster.com/cart.php?a=add&pid=7',
      price: '$2.60 USD',
      savePrice: '$9.99',
      savePercentage: 'Save 90%',
      features: ['Disc Space: 500MB',
       'Traffic: Unlimited',
      'Control Panel: cPanel',
      'Mail Accounts: 15',
      'Databases MySQL: 5',
      'FTP Accounts: 5',
      'Subdomains: 10',
      'Permitted domains: 1',
      'Additional Domains: 2',
      'Domain Aliases: 2',
      'Includes SSL Certificate Free',
      'Idera Servers by V8-925 ®',
      'DDoS Protection: Integrated',
      'Backup: Automatic',
      'Money back guarantee 30 days',
      'Technical Support 24/7',
      'Datacenters: Miami FL.',
  ],
    },
    {
      id: 2,
      name: 'Hosting Cpanel Medium',
      url: 'https://my.donhoster.com/cart.php?a=add&pid=8',
      price: '$4.99 USD',
      savePrice: '$9.99',
      savePercentage: 'Save 90%',
      features: ['Disc Space: 2GB',
        'Traffic: Unlimited',
        'Control Panel: cPanel',
        'Mail Accounts: 30',
        'Databases MySQL: 10',
        'FTP Accounts: 15',
        'Subdomains: 25',
       'Permitted domains: 1',
        'Additional Domains: 5',
        'Domain Aliases: 5',
        'Includes SSL Certificate Free',
        'Idera Servers by V8-925 ®',
        'DDoS Protection: Integrated',
        'Backup: Automatic',
        'Money back guarantee 30 days',
        'Technical Support 24/7',
        'Datacenters: Miami FL.',],
    },
    {
      id: 3,
      name: 'Hosting Cpanel Large',
      url: 'https://my.donhoster.com/cart.php?a=add&pid=9',
      price: '$7.99 USD',
      savePrice: '$9.99',
      savePercentage: 'Save 90%',
      features: ['Disc Space: 2GB',
        'Traffic: Unlimited',
        'Control Panel: cPanel',
        'Mail Accounts: 30',
        'Databases MySQL: 10',
        'FTP Accounts: 5',
        'Subdomains: 20',
        'Permitted domains: 1',
        'Additional Domains: 5',
        'Domain Aliases: 5',
        'Includes SSL Certificate Free',
        'Idera Servers by V8-925 ®',
        'DDoS Protection: Integrated',
        'Backup: Automatic',
        'Money back guarantee 30 days',
        'Technical Support 24/7',
        'Datacenters: Miami FL.',],
    },
    {
      id: 4,
      name: 'Hosting Cpanel Extra',
      url: 'https://my.donhoster.com/cart.php?a=add&pid=10',
      price: '$23.99 USD',
      savePrice: '$9.99',
      savePercentage: 'Save 90%',
      features: ['Disc Space: 3GB',
        'Traffic: Unlimited',
        'Control Panel: cPanel',
        'Mail Accounts: 40',
        'Databases MySQL: 15',
        'FTP Accounts: 10',
        'Subdomains: 25',
        'Permitted domains: 1',
        'Additional Domains: 7',
        'Domain Aliases: 7',
        'Includes SSL Certificate Free',
        'Idera Servers by V8-925 ®',
        'DDoS Protection: Integrated',
        'Backup: Automatic',
        'Money back guarantee 30 days',
        'Technical Support 24/7',
        'Datacenters: Miami FL.' ,],
    },

  ];

  export default hosting;